import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer,generateOrEdit,buildEditPrompt,buildBasePrompt,buildShotPrompt} from '../server.mjs';
const png='data:image/png;base64,aGVsbG8=';
test('prompt keeps selected modifications constrained and identifies synthetic reference',()=>{const p=buildEditPrompt({year:'2024',make:'BMW',model:'M4',angle:'Front 3/4',modifications:['Satin British Racing Green vehicle color wrap','20% VLT tint']});assert.match(p,/Preserve the exact source vehicle/);assert.match(p,/Satin British Racing Green/);assert.match(buildBasePrompt({year:2024,make:'BMW',model:'M4'}),/AI-created reference/)});
test('different window tint VLTs remain separate and visually proportional',()=>{const p=buildEditPrompt({year:2024,make:'Honda',model:'CR-V',angle:'Front 3/4',modifications:['15% VLT tint on front side windows','15% VLT tint on rear side windows','15% VLT tint on rear windshield','75% VLT tint on windshield']});assert.match(p,/each listed glass area as a separate panel/);assert.match(p,/15% must be visibly much darker than 75%/);assert.match(p,/Do not average, normalize, equalize/);assert.match(p,/Preserve the original appearance of every unlisted glass area/);for(const zone of ['front side windows','rear side windows','rear windshield','windshield'])assert.match(p,new RegExp(zone))});
test('calipers can match selected wrap color and wheels are omitted',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');assert.match(html,/value="wrap">Match wrap color/);assert.match(js,/choice==='wrap'\?wrapHex\(\)/);assert.match(js,/wrap-matched/);assert.doesNotMatch(html,/wheelStyles|Wheels & calipers|Wheel finish/);assert.doesNotMatch(js,/function wheelSvg|wheelToggle|wheelStyles/);assert.match(css,/grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/)});
test('photo edit sends uploaded photo directly to edit endpoint',async()=>{const calls=[];const result=await generateOrEdit({body:{year:2024,make:'BMW',model:'M4',image:png,angle:'Side',modifications:['Satin wrap']},env:{OPENAI_API_KEY:'test'},fetcher:async(url,opts)=>{calls.push([url,opts]);return{ok:true,json:async()=>({data:[{b64_json:'cmVzdWx0'}]})}}});assert.equal(calls.length,1);assert.match(calls[0][0],/images\/edits$/);assert.ok(calls[0][1].body instanceof FormData);assert.equal(calls[0][1].body.get('model'),'gpt-image-2.5-sunburst');assert.equal(calls[0][1].body.get('image[]').type,'image/png');assert.equal(result.image,'data:image/png;base64,cmVzdWx0');assert.equal(result.originalImage,png)});
test('photo-free generation creates a reference then edits that reference',async()=>{const calls=[];const result=await generateOrEdit({body:{year:2024,make:'BMW',model:'M4',angle:'Front 3/4',modifications:['Satin wrap']},env:{OPENAI_API_KEY:'test'},fetcher:async(url,opts)=>{calls.push([url,opts]);return{ok:true,json:async()=>({data:[{b64_json:'cmVm'}]})}}});assert.equal(calls.length,2);assert.match(calls[0][0],/images\/generations$/);assert.match(calls[1][0],/images\/edits$/);assert.equal(result.originalImage,'data:image/png;base64,cmVm');assert.equal(result.generatedReference,true)});
test('no modifications returns reference without edit call',async()=>{let calls=0;const result=await generateOrEdit({body:{year:2024,make:'BMW',model:'M4',baseImage:png,modifications:[]},env:{OPENAI_API_KEY:'test'},fetcher:async()=>{calls++;throw Error('should not call')}});assert.equal(calls,0);assert.equal(result.image,png)});
test('frontend guides customers through photos, customization, review, and saved concepts',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');for(const id of ['newProject','photoInput','reviewBuild','reviewModal','confirmGenerate','compareRange','variation','downloadCurrent','resetConfig','backProjects','tintZones','tintToggle','caliperShape','caliperSummary','tintStatus','wrapStatus','additional'])assert.match(html,new RegExp(`id="${id}"|data-angle="${id}"`));for(const label of ['Front','Side','Rear','Additional'])assert.match(html,new RegExp(`>${label}<`));assert.match(js,/no customer photo/i);assert.match(css,/@media\(max-width:740px\)/);assert.match(js,/indexedDB/);assert.match(js,/Gemini API key/);assert.match(js,/const tintAreas/);assert.match(js,/function openBuildReview/);assert.match(js,/function selectedTintMods/);assert.doesNotMatch(html,/type="range"[^>]*id="tint/i);assert.doesNotMatch(html,/body-icon|Body & stance|data-angle="interior"/)});


test('tint has two grouping modes and one prominent shade reference at a time',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');for(const id of ['photoGuideModal','continuePhotoUpload','tintGrouping','tintTargets','tintFeature','tintCustomInput','caliperShape','customCaliper'])assert.match(html,new RegExp(`id="${id}"`));for(const label of ['All windows match','Choose each area','wipe the camera lens'])assert.match(html,new RegExp(label));assert.doesNotMatch(html,/Pair side windows/);assert.match(js,/function setTintGrouping/);assert.match(js,/function tintTargetAreas/);assert.match(js,/tint-\$\{file\}\.jpg/);assert.match(js,/function syncCaliperPreview/);assert.match(js,/\$\('#uploadTrigger'\)\.onclick=showPhotoGuide/);assert.match(css,/color-scheme:light/);assert.match(css,/\.tint-feature-image img/);assert.match(css,/@media\(max-width:740px\)/)});

test('static build points to the separate API and Node API allows only the configured static origin',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const server=await fs.readFile(new URL('../server.mjs',import.meta.url),'utf8');const yaml=await fs.readFile(new URL('../render.yaml',import.meta.url),'utf8');const build=await fs.readFile(new URL('../build-static.mjs',import.meta.url),'utf8');assert.match(html,/config\.js/);assert.match(build,/page\.replace\(configScript, `<script>window\.CARSTUDIO_API_BASE/);assert.match(js,/function apiUrl|const apiUrl=/);assert.match(js,/fetch\(apiUrl\(url\)/);assert.match(server,/CARSTUDIO_ALLOWED_ORIGIN/);assert.match(server,/access-control-allow-origin/);assert.match(yaml,/runtime: static/);assert.match(yaml,/name: carstudio-api/);assert.match(yaml,/https:\/\/carstudio-api-5397\.onrender\.com/)});

test('API accepts both current and clean public frontend origins',async()=>{const fs=await import('node:fs/promises');const server=await fs.readFile(new URL('../server.mjs',import.meta.url),'utf8');const yaml=await fs.readFile(new URL('../render.yaml',import.meta.url),'utf8');assert.match(server,/split\(','\)/);assert.match(yaml,/https:\/\/carstudio-demo\.onrender\.com,https:\/\/carstudio-shop\.onrender\.com/)})

test('wrap colors page through a 4 by 2 carousel and photo controls show three-quarter views',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');for(const id of ['colorViewport','colorPrev','colorNext','colorPagination'])assert.match(html,new RegExp(`id="${id}"`));assert.match(html,/class="toast hidden" id="toast"/);assert.match(html,/Front corner three-quarter angle/);assert.match(html,/Rear corner three-quarter angle/);assert.match(html,/Front · 3\/4 angle/);assert.match(html,/Rear · 3\/4 angle/);assert.match(js,/\['Rose copper'/);assert.match(js,/function setColorPage/);assert.match(css,/\.swatch-page\{[^}]*repeat\(4,minmax\(0,1fr\)\)/)});

test('current paint is used in model references and preserved during edits',()=>{const base=buildBasePrompt({year:'2024',make:'BMW',model:'M4',currentColor:'Alpine White'});assert.match(base,/current factory paint color: Alpine White/);const edit=buildEditPrompt({year:'2024',make:'BMW',model:'M4',currentColor:'Alpine White',modifications:['Satin emerald vehicle color wrap']});assert.match(edit,/current paint color is Alpine White; preserve it unless a color wrap is selected/)});
test('review presents each modification as its own row and tint areas can be cleared individually',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(html,/id="currentColor"/);assert.doesNotMatch(html,/id="trim"/);assert.match(js,/mods\.map\(mod=>`<div class=\"review-row\"><b>\$\{safe\(reviewLabel\(mod\)\)\}/);assert.match(js,/choices=\['none','5','15','20','35','50','70','custom'\]/);assert.match(js,/v==='none'\?'off'/);assert.match(js,/scheduleVehicleReference\(\)/);assert.match(js,/project\.generatedRefs\.front34=result\.originalImage/)});

test('Gemini edits the uploaded customer photo with the selected specification',async()=>{const calls=[];const result=await generateOrEdit({body:{year:2024,make:'BMW',model:'M4',currentColor:'Alpine White',image:png,angle:'Side',modifications:['Satin British Racing Green wrap','20% VLT tint']},env:{GEMINI_API_KEY:'test'},fetcher:async(url,opts)=>{calls.push([url,opts]);return{ok:true,json:async()=>({candidates:[{content:{parts:[{inlineData:{mimeType:'image/png',data:'Z2VuZXJhdGVk'}}]}}]})}}});assert.equal(calls.length,1);assert.match(calls[0][0],/models\/gemini-3\.1-flash-image:generateContent$/);assert.equal(calls[0][1].headers['x-goog-api-key'],'test');const payload=JSON.parse(calls[0][1].body);assert.equal(payload.generationConfig.responseModalities[0],'IMAGE');assert.equal(payload.contents[0].parts[1].inline_data.data,'aGVsbG8=');assert.match(payload.contents[0].parts[0].text,/Preserve the exact source vehicle/);assert.match(payload.contents[0].parts[0].text,/20% VLT tint/);assert.equal(result.image,'data:image/png;base64,Z2VuZXJhdGVk');assert.equal(result.originalImage,png)});

test('Gemini creates a model-based reference and then applies requested modifications',async()=>{const calls=[];const result=await generateOrEdit({body:{year:2024,make:'BMW',model:'M4',angle:'Front 3/4',modifications:['Satin wrap']},env:{GEMINI_API_KEY:'test'},fetcher:async(url,opts)=>{calls.push([url,JSON.parse(opts.body)]);return{ok:true,json:async()=>({candidates:[{content:{parts:[{inline_data:{mime_type:'image/png',data:`image${calls.length}`}}]}}]})}}});assert.equal(calls.length,2);assert.equal(calls[0][1].contents[0].parts.length,1);assert.match(calls[0][1].contents[0].parts[0].text,/AI-created reference/);assert.equal(calls[1][1].contents[0].parts[1].inline_data.data,'image1');assert.equal(result.originalImage,'data:image/png;base64,image1');assert.equal(result.image,'data:image/png;base64,image2');assert.equal(result.generatedReference,true)});

test('live UI and server contain no demo access flow or preview cap',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const server=await fs.readFile(new URL('../server.mjs',import.meta.url),'utf8');assert.doesNotMatch(html,/SHOP DEMO|accessModal|demo code|demo access/i);assert.doesNotMatch(js,/accessCode|accessModal|x-carstudio-demo-code|preview limit/i);assert.doesNotMatch(server,/CARSTUDIO_DEMO_CODE|MAX_GENERATIONS_PER_WINDOW|generationCounts|demo access|preview limit/i)});

test('results preserve the source frame, create one image initially, and generate Shots from the saved concept',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');assert.match(html,/id="shotsButton"/);assert.match(html,/id="shotsModal"/);assert.match(html,/id="shotsStatus"/);for(const angle of ['front34','side','rear34','additional'])assert.match(html,new RegExp(`data-angle="${angle}"`));assert.doesNotMatch(js,/function generationPlan\(\)/);assert.match(js,/async function generate\(variation=false\)[\s\S]*?const payload=/);assert.match(js,/shots:\[\{id:uuid\(\),angle,title:angles\[angle\]/);assert.match(js,/shotMode:true/);assert.match(js,/image:c\.image/);assert.match(js,/function alignImageToFrame/);assert.match(js,/function renderShots\(c\)/);assert.match(html,/id="shotsStrip"/);assert.match(js,/function createProject\(\)[^}]*switchView\('editor'\)\}/);assert.doesNotMatch(js,/\$\('#projectTitle'\)\.focus\(\)/);assert.match(css,/\.concept-strip\{[^}]*overflow-x:auto/);assert.match(css,/\.concept-tile\{flex:0 0 clamp/);assert.match(css,/\.split-handle span\{[^}]*color:#fff/);assert.match(css,/\.control-footer\{position:fixed/);assert.match(html,/class="split-grip"/);assert.match(js,/hasComparison=Boolean/);assert.match(js,/if\(hasComparison\)applyCompare/);assert.match(js,/clipPath='none'/);assert.doesNotMatch(html,/angle-badge|id="angleBadge"|\bAI\b|AI-generated/i);assert.doesNotMatch(js,/angleBadge|\bAI\b|AI-generated/i)});
test('Shots prompt locks selected changes to the generated concept and changes only viewpoint',()=>{const prompt=buildShotPrompt({year:2024,make:'BMW',model:'M4',angle:'Side profile',modifications:['15% VLT tint on rear side windows','75% VLT tint on windshield','Satin green wrap']});assert.match(prompt,/single authoritative reference image/);assert.match(prompt,/tint darkness by window area/);assert.match(prompt,/Only the camera viewpoint may change/);assert.match(prompt,/75% VLT tint on windshield/)});
test('studio canvas and customer consultation are combined in the editor',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');for(const id of ['headerConceptCount','briefChangeCount','briefStatus','briefLines'])assert.match(html,new RegExp(`id="${id}"`));assert.match(html,/CUSTOMER PROJECT/);assert.match(html,/class="workspace-tabs"/);assert.match(js,/scrollIntoView\(\{behavior:'smooth',block:'start'\}\)/);assert.match(js,/function renderBuildBrief\(\)/);assert.match(js,/concept\.modifications\.map\(mod=>`<div class="concept-mod-row"/);assert.match(css,/grid-template-columns:minmax\(0,1\.45fr\) minmax\(340px,\.88fr\)/);assert.match(css,/\.preview-column\{grid-column:1;grid-row:1/);assert.match(css,/@media\(max-width:740px\)\{\.editor-layout\{display:flex!important/)});
test('vehicle-first interface follows the supplied proposal screen while preserving working service controls',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');for(const category of ['wrap','tint','calipers']){assert.match(html,new RegExp(`data-service-tab="${category}"`));assert.match(html,new RegExp(`data-service="${category}"`))}assert.match(html,/id="vehicleSpecs"/);assert.match(html,/Add to proposal/);assert.match(js,/function renderVehicleSpecs\(\)/);assert.ok(js.includes("key==='clear'?'clear'"));assert.match(js,/classList\.toggle\('hidden',!concept\)/);assert.match(js,/dataset\.serviceTab/);assert.match(js,/renderVehicleSpecs\(\);updateNote\(\);persist\(\);if\(\['year','make','model','currentColor'\]/);assert.match(css,/\.preview-column\{grid-column:1!important;grid-row:1!important/);assert.match(css,/\.service-tab\.active:after/);assert.match(css,/grid-template-columns:repeat\(8,minmax\(0,1fr\)\)/);assert.match(css,/@media\(max-width:740px\)/)});
