import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer,generateOrEdit,buildEditPrompt,buildBasePrompt} from '../server.mjs';
const png='data:image/png;base64,aGVsbG8=';
test('prompt keeps selected modifications constrained and identifies synthetic reference',()=>{const p=buildEditPrompt({year:'2024',make:'BMW',model:'M4',angle:'Front 3/4',modifications:['Satin British Racing Green vehicle color wrap','20% VLT tint']});assert.match(p,/Preserve the exact source vehicle/);assert.match(p,/Satin British Racing Green/);assert.match(buildBasePrompt({year:2024,make:'BMW',model:'M4'}),/AI-created reference/)});
test('photo edit sends uploaded photo directly to edit endpoint',async()=>{const calls=[];const result=await generateOrEdit({body:{year:2024,make:'BMW',model:'M4',image:png,angle:'Side',modifications:['Satin wrap']},env:{OPENAI_API_KEY:'test'},fetcher:async(url,opts)=>{calls.push([url,opts]);return{ok:true,json:async()=>({data:[{b64_json:'cmVzdWx0'}]})}}});assert.equal(calls.length,1);assert.match(calls[0][0],/images\/edits$/);assert.ok(calls[0][1].body instanceof FormData);assert.equal(calls[0][1].body.get('model'),'gpt-image-2.5-sunburst');assert.equal(calls[0][1].body.get('image[]').type,'image/png');assert.equal(result.image,'data:image/png;base64,cmVzdWx0');assert.equal(result.originalImage,png)});
test('photo-free generation creates a reference then edits that reference',async()=>{const calls=[];const result=await generateOrEdit({body:{year:2024,make:'BMW',model:'M4',angle:'Front 3/4',modifications:['Satin wrap']},env:{OPENAI_API_KEY:'test'},fetcher:async(url,opts)=>{calls.push([url,opts]);return{ok:true,json:async()=>({data:[{b64_json:'cmVm'}]})}}});assert.equal(calls.length,2);assert.match(calls[0][0],/images\/generations$/);assert.match(calls[1][0],/images\/edits$/);assert.equal(result.originalImage,'data:image/png;base64,cmVm');assert.equal(result.generatedReference,true)});
test('no modifications returns reference without edit call',async()=>{let calls=0;const result=await generateOrEdit({body:{year:2024,make:'BMW',model:'M4',baseImage:png,modifications:[]},env:{OPENAI_API_KEY:'test'},fetcher:async()=>{calls++;throw Error('should not call')}});assert.equal(calls,0);assert.equal(result.image,png)});
test('frontend contains the full reachable shop flow and responsive entry points',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');for(const id of ['newProject','photoInput','generate','compareRange','variation','downloadCurrent','resetConfig','backProjects','tintZones','tintToggle','wheelStyles','tintStatus','wrapStatus','wheelStatus','bodyStatus'])assert.match(html,new RegExp(`id=\"${id}\"`));assert.match(js,/no customer photo/i);assert.match(css,/@media\(max-width:740px\)/);assert.match(js,/indexedDB/);assert.match(js,/API_KEY/);assert.match(js,/const tintAreas/);assert.match(js,/Very dark/);assert.doesNotMatch(html,/type=\"range\"[^>]*id=\"tint/i)});

test('wheel styles use accessible visual cards and stance reference can be generated',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');assert.match(html,/id="wheelStyles"><\/div>/);assert.match(html,/id="createStanceReference"/);assert.match(html,/id="stanceOptions"/);assert.match(js,/function wheelSvg/);for(const label of ['Many thin spokes','Paired spokes','Crossed spoke grid','Swept fan blades'])assert.ok(js.includes(label));assert.match(js,/function stanceSvg/);assert.match(js,/Vehicle-specific side reference created/);assert.match(css,/\.wheel-drawing svg/);assert.match(css,/\.stance-option\.active/)});

test('tint grouping, camera guidance, light workspace, and live caliper preview are wired',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const css=await fs.readFile(new URL('../public/styles.css',import.meta.url),'utf8');for(const id of ['photoGuideModal','continuePhotoUpload','tintGrouping','tintTargets','tintCustomInput','caliperShape','customCaliper'])assert.match(html,new RegExp(`id="${id}"`));for(const label of ['All windows match','Pair side windows','Choose each area','wipe the camera lens'])assert.match(html,new RegExp(label));assert.match(js,/function setTintGrouping/);assert.match(js,/function tintTargetAreas/);assert.match(js,/function syncCaliperPreview/);assert.match(js,/\$\('#uploadTrigger'\)\.onclick=showPhotoGuide/);assert.match(css,/color-scheme:light/);assert.match(css,/@media\(max-width:740px\)/)});


test('static build points to the separate API and Node API allows only the configured static origin',async()=>{const fs=await import('node:fs/promises');const html=await fs.readFile(new URL('../public/index.html',import.meta.url),'utf8');const js=await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8');const server=await fs.readFile(new URL('../server.mjs',import.meta.url),'utf8');const yaml=await fs.readFile(new URL('../render.yaml',import.meta.url),'utf8');assert.match(html,/config\.js/);assert.match(js,/function apiUrl|const apiUrl=/);assert.match(js,/fetch\(apiUrl\(url\)/);assert.match(server,/CARSTUDIO_ALLOWED_ORIGIN/);assert.match(server,/access-control-allow-origin/);assert.match(yaml,/runtime: static/);assert.match(yaml,/name: carstudio-api/)});
